azure:
  activedirectory:
    clientId: 5be39bef-6ca2-4df9-9bf0-2e58fa7c6103
    clientSecret: wmCDXwdrr3hxPtcchOwF9qRCU2+e649Myqi1sGj0Q6w=
    activeDirectoryGroups: group1,group2

logging:
  level:
    org.springframework.security: DEBUG