azure:
  activedirectory:
    clientId: dfc50f18-c112-4326-9def-3894934dd191
    clientSecret: qylnddSZTaE+UKOTq9/0NURm5IoYVpROGPtt2Pj2h0g=
    activeDirectoryGroups: group1,group2

logging:
  level:
    org.springframework.security: DEBUG